#' @export
makeQxDataFrame = function(..., YOB=1972, Period=NA) {
  data=list(...);
  names(data) = lapply(data, function(t) t@name);
  if (missing(Period)) {
    cat("Year of birth: ", YOB, "\n");
    data = lapply(data, function(t) cbind(x=ages(t), y=deathProbabilities(t, YOB=YOB)))
  } else {
    cat("Period: ", Period,"\n");
    data = lapply(data, function(t) cbind(x=ages(t), y=periodDeathProbabilities(t, Period=Period)))
  }

  list.names = names(data)
  lns <- sapply(data, nrow)
  data <- as.data.frame(do.call("rbind", data))
  data$group <- rep(list.names, lns)
  data
}

#' Plot multiple valuation tables (life tables) in one plot
#'
#' \code{plotValuationTables} prints multiple life tables (objects of child classes of \code{valuationTable}) in one log-linear plot, with a legend showing the names of the tables.
#'
#' @param data First life table to be plotted. Either a \code{data.frame} generated by \code{makeQxDataFrame} or a \code{valuationTable} object
#' @param ... Additional life tables to be plotted (if \code{data} is a \code{valuationTable} object)
#' @param title The plot title
#' @param legend.position The position of the legend (default is \code{c(0.9,0.1)})
#' @param legend.key.width The keywith of the lines in the  legend (default is \code{unit(25,"mm")})
#'
#' @export
plotValuationTables = function(data, ..., title = "", legend.position=c(0.9,0.1), legend.key.width = unit(25, "mm")) {
  if (!is.data.frame(data)) {
    data = makeQxDataFrame(data, ...);
  }

  pl = ggplot(data, aes(x = x, y = y, colour = data$group)) +
    theme_bw() +
    theme(
      plot.title = element_text(size=18, face="bold"),
      legend.title = element_text(size=14, face="bold.italic"),
      # legend in bottom right corner of the plot
      legend.justification=c(1,0), legend.position=legend.position,
      # No box around legend entries
      legend.key = element_blank(),
      legend.key.width = legend.key.width,
      legend.background = element_rect(colour="gray50", linetype="solid")
    ) +
    geom_line() +
    scale_y_log10(
      name=expression(paste("Sterbewahrscheinlichkeit  ", q[x])),
      breaks = scales::trans_breaks('log10', function(x) 10^x),
      labels = scales::trans_format('log10', scales::math_format(10^.x))
      #minor_breaks = log(c(sapply(x, function(x) seq(0, x, x/10))), 10)
    ) +
    scale_x_continuous(
      name="Alter",
      #breaks = function (limits) scales::trans_breaks('', function(x) 10^x),
      breaks = function (limits) seq(max(min(limits),0),max(limits),5),
      minor_breaks = function (limits) seq(max(round(min(limits)),0),round(max(limits)),1),
      #labels = scales::trans_format('log10', scales::math_format(10^.x))

    ) +
    annotation_logticks(sides="lr") +
    xlab("Alter") + labs(colour="Sterbetafel");
  if (title != "") {
    pl = pl + ggtitle(title);
  }
  pl
}
#
# plotValuationTables(mort.AT.census.1869.male, mort.AT.census.1869.female, mort.AT.census.2011.male, mort.AT.census.2011.female, AVOe2005R.male, AVOe2005R.female, YOB=1972,title="Vergleich österreichische Sterbetafeln, YOB=1972 (bei Generationentafeln)")
#
# plotValuationTables(mort.AT.census.2001.male, AVOe2005R.male, YOB=1972, title="Vergleich österreichische Sterbetafeln")
#  plotValuationTables(getCohortTable(AVOe2005R.male, YOB=1972), getCohortTable(AVOe2005R.male, YOB=2016), title="Vergleich österreichische Sterbetafeln")
